trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: fitnessapp
  imageTag: $(Build.BuildId)

steps:

# Install Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

# Install Dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Build and Push Docker Image to ACR
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: 'Dockerfile'
    containerRegistry: 'ACR Connection'
    tags: |
      $(imageTag)
      latest

# Deploy to AKS
- task: KubernetesManifest@1
  displayName: 'Deploy to AKS'
  inputs:
    action: deploy
    kubernetesServiceConnection: 'AzureAKS'
    namespace: suwetha-ns
    manifests: |
      k8s/namespace.yml
      k8s/app-deployment.yml
      k8s/configmap.yml
      k8s/mongodb-deployment.yaml
    containers: |
      fitnessacr.azurecr.io/$(imageRepository):$(imageTag)

# Slack Notification (Success or Failure)
- task: Bash@3
  displayName: 'Slack Notification'
  condition: always()
  inputs:
    targetType: 'inline'
    script: |
      if [ "$(Agent.JobStatus)" = "Succeeded" ]; then
        MESSAGE="✅ Azure DevOps Pipeline Succeeded
        
        Project: $(System.TeamProject)
        Repository: $(Build.Repository.Name)
        Branch: $(Build.SourceBranchName)
        Build Number: $(Build.BuildNumber)"
      else
        MESSAGE="❌ Azure DevOps Pipeline Failed
        
        Project: $(System.TeamProject)
        Repository: $(Build.Repository.Name)
        Branch: $(Build.SourceBranchName)
        Build Number: $(Build.BuildNumber)"
      fi

      curl -X POST \
        -H "Content-Type: application/json" \
        --data "{\"text\":\"$MESSAGE\"}" \
        "$SLACK_WEBHOOK_URL"
  env:
    SLACK_WEBHOOK_URL: $(SLACK_WEBHOOK_URL)