apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-app
  namespace: suwetha-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
      annotations:
        ad.datadoghq.com/fitness-tracker-app.logs: >-
          [{"source":"nodejs","service":"fitness-tracker-service"},
           {"source":"nodejs","service":"fitness-tracker-app"}]
    spec:
      # nodeSelector:
      #   training: "devops"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: training
      #               operator: In
      #               values:
      #                 - devops

      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 1
      #         preference:
      #           matchExpressions:
      #             - key: training
      #               operator: In
      #               values:
      #                 - devops
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 10
      #         podAffinityTerm:
      #           labelSelector:
      #             matchLabels:
      #               app: fitness-tracker-app
      #           topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "train"
        operator: "Equal"
        value: "devops"
        effect: "NoSchedule"         
      containers:
        - name: fitness-tracker-app
          image: image: fitnessacr.azurecr.io/fitnessapp:latest
        # image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits: 
              memory: "512Mi"
              cpu: "200m"
          # ✔ All configMap vars removed
          # ✔ Direct env variables added
          envFrom:
            - configMapRef:
                name: fitness-configmap
            # Datadog APM (tracing) env variables
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_ENV
              value: "production"
            - name: DD_SERVICE
              value: "fitness-tracker-app"
            - name: DD_VERSION
              value: "1.0.0"
---

apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
  namespace: suwetha-ns
spec:
  selector:
    app: fitness-tracker-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
